apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: users-api-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: users-api
  endpoints:
  - port: http-metrics
    path: /actuator/prometheus
    interval: 15s
    scheme: http