{
 "title": "sony dashboard metrics API",
 "time": { "from": "2025-07-07T15:16:02.207Z", "to": "2025-07-07T16:20:52.255Z" },
 "panels": [
  {
   "title": "Pod memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{pod=~\"users-api-5f784cbcf5-l7sfv|users-api-5f784cbcf5-kt57t|users-api-5f784cbcf5-bnqtl|users-api-5f784cbcf5-pf2hl\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"users-api-5f784cbcf5-bnqtl|users-api-5f784cbcf5-kt57t\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status) (rate(nginx_ingress_controller_requests{status=\"500\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress RPS by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_seconds_count{uri!~\"/health\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses by http status and method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(status, method) (http_server_requests_seconds_count{uri!~\"/health\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}